//
// Created by Adrien Blanchet on 14/04/2023.
//

#ifndef SIMPLEMODMANAGER_SIMPLEMODMANAGER_H
#define SIMPLEMODMANAGER_SIMPLEMODMANAGER_H

void runGui();


#endif //SIMPLEMODMANAGER_SIMPLEMODMANAGER_H
