function(cmake_info message)
    if (cmake_VERBOSE)
        message("Build-Info: ${message}")
    endif ()
endfunction()

function(cmake_warning message)
    if (cmake_VERBOSE)
        message(WARNING "${message}")
    endif ()
endfunction()

function(cmake_panic message)
    message(FATAL_ERROR "${message}")
endfunction()
